# Generated by Django 3.1.3 on 2021-01-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='discription',
            new_name='description',
        ),
    ]
